### [Random Forest for Stock Market Prediction](https://wire.insiderfinance.io/using-random-forest-for-stock-market-prediction-79cf3803c840)

In [1]:
!pip install -qq --no-deps pandas numpy yfinance scikit-learn

In [2]:
import sys

IN_COLAB = "google.colab" in sys.modules

import warnings
warnings.filterwarnings("ignore")

from IPython.display import display, HTML

import numpy as np
import pandas as pd

import yfinance as yf

np.random.seed(42)
np.set_printoptions(precision=4, suppress=True)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", None)
pd.set_option("display.float_format", "{:.4f}".format)

%autosave 10

Autosaving every 10 seconds

#### **Collect Market Data**

In [3]:
data = yf.download("SPY", period="5y", multi_level_index=False, progress=False)
data['Returns'] = data['Close'].pct_change()

display(data.sample(20))

              Close     High      Low     Open     Volume  Returns
Date
2022-12-22 364.9762 370.2392 359.2722 367.2098  100120900  -0.0143
2021-08-26 418.1628 420.5991 418.0691 420.3648   57829600  -0.0059
2021-06-16 394.2435 396.8213 392.1981 396.5972   80386100  -0.0056
2021-07-02 406.4124 406.7685 403.4138 404.4915   57697700   0.0076
2025-10-31 678.1983 681.2012 675.3943 681.1614   87164100   0.0033
2022-12-06 375.8182 381.6965 373.7284 381.1526   77972200  -0.0144
2025-06-27 609.7381 611.2057 605.6925 607.7252   86258400   0.0050
2023-07-31 442.1705 442.5278 440.4898 441.8034   62040400   0.0019
2026-02-12 679.4146 693.4562 678.5170 692.3492  118829000  -0.0154
2025-05-16 587.4655 587.7621 582.6013 584.5489   76052100   0.0063
2022-12-01 388.7486 391.2488 386.2389 390.0750   76398200  -0.0007
2025-06-05 586.3286 592.2111 584.3512 590.8567   92278700  -0.0048
2022-01-13 438.2112 446.0881 437.1830 445.4372   91173100  -0.0138
2024-08-27 549.9866 550.4763 546.8134 547.9592   32693900   0.0014
2025-06-25 602.0136 603.4911 600.4469 602.7969   62114800   0.0006
2022-08-30 378.4434 384.0410 376.3431 383.8034   85652400  -0.0110
2025-02-21 591.3616 601.5734 590.8983 601.4354   76519800  -0.0171
2023-08-24 421.9836 430.0293 421.9545 429.5174   88517300  -0.0139
2022-10-25 367.3158 367.6307 361.3516 361.4661   78846300   0.0160
2024-05-14 510.8670 511.3845 508.1921 508.7291   57535900   0.0046

#### **Feature Engineering**

In [4]:
data['SMA20'] = data['Close'].rolling(20).mean()
data['SMA50'] = data['Close'].rolling(50).mean()
data['Momentum'] = data['Close'] - data['Close'].shift(10)
data['Volatility'] = data['Returns'].rolling(20).std()

display(data.sample(20))

,Close,High,Low,Open,Volume,Returns,SMA20,SMA50,Momentum,Volatility
Date,,,,,,,,,,
2023-07-27,437.0513,443.7642,436.1433,443.3585,92194400,-0.0066,432.5083,419.7181,2.8300,0.0052
2023-12-13,456.0498,456.3018,449.8657,450.2244,93278000,0.0138,442.5350,426.6426,15.4020,0.0044
2021-04-12,384.4648,384.7356,383.1199,383.7270,56704900,0.0004,NaN,NaN,NaN,NaN
2025-04-04,499.5533,519.9100,499.3358,517.7349,217965100,-0.0585,552.0195,574.8050,-58.0347,0.0202
2021-11-01,432.4563,433.0767,430.7266,432.7007,48433600,0.0017,420.0284,417.9894,12.0796,0.0056
2024-02-23,494.2484,496.4674,493.5185,495.6304,61321800,0.0007,482.9407,470.3178,9.2747,0.0088
2025-06-11,594.5444,598.2025,592.4781,597.3423,73658200,-0.0029,585.5065,557.4131,13.4755,0.0076
2024-09-06,529.2234,540.2318,528.3224,538.6060,68493800,-0.0168,541.2304,537.7272,-15.5333,0.0095
2025-08-25,637.0663,639.8626,636.9473,638.6231,51274300,-0.0044,631.7072,620.4752,6.4949,0.0076
2026-01-20,675.7346,682.9050,674.7273,679.6339,111623300,-0.0204,686.4992,678.0671,-10.1124,0.0065
2021-12-15,442.3831,442.6275,433.1143,435.6336,116899300,0.0156,436.4900,430.9080,18.8948,0.0116
2023-01-10,374.4284,374.4955,370.2966,371.2361,65358100,0.0070,369.5960,372.6450,7.3528,0.0123
2022-12-30,366.6155,366.7593,362.7809,364.8995,84022200,-0.0026,372.5504,371.5838,-5.1949,0.0116
2023-10-13,418.2476,423.0456,416.6773,421.8436,95143100,-0.0050,417.9015,425.0688,3.8965,0.0077
2021-08-16,418.8281,418.9593,414.9862,416.5417,73740000,0.0024,412.6526,405.1270,8.7894,0.0050
2024-01-26,474.3559,476.0201,473.5092,474.5311,76641600,-0.0013,464.3216,454.2237,10.7638,0.0059
2022-10-14,341.2739,353.3263,340.6346,351.6945,123737000,-0.0228,351.4545,373.6190,0.4295,0.0172
2023-01-05,363.6917,366.0499,363.0973,365.9349,76970500,-0.0114,370.1115,372.1687,-1.1120,0.0111
2023-12-05,442.5767,443.5363,440.8998,441.2778,69793500,-0.0002,436.1266,422.5144,2.2681,0.0063
2025-10-24,673.4156,674.6287,671.8247,672.6301,74356500,0.0082,663.7024,653.1649,24.0928,0.0085

#### **Define Target Variable**

In [5]:
data['Target'] = (data['Close'].shift(-1) > data['Close']).astype(int)

display(data.sample(20))

,Close,High,Low,Open,Volume,Returns,SMA20,SMA50,Momentum,Volatility,Target
Date,,,,,,,,,,,
2021-08-17,416.0826,416.9446,413.0934,416.2700,92673900,-0.0066,413.2607,405.5623,2.7080,0.0046,0
2022-11-15,380.2651,383.9104,376.4480,382.8035,93194500,0.0085,364.4749,360.9119,13.3311,0.0182,0
2021-05-27,391.6097,392.9453,391.3295,392.4317,56707700,0.0005,388.3870,NaN,8.4152,0.0090,1
2024-09-09,535.1489,536.4222,531.4958,533.4252,40445800,0.0112,541.8876,537.7280,-15.3959,0.0097,1
2025-05-02,560.3365,561.9381,556.0061,558.3295,60717300,0.0148,528.9810,549.7121,39.8926,0.0321,0
2021-07-14,408.7737,410.3480,407.5275,409.8607,64130400,0.0015,401.2703,394.8721,8.0023,0.0063,0
2025-10-07,665.3316,669.1797,663.8898,668.7322,72020100,-0.0037,658.7016,644.3818,5.8765,0.0039,1
2025-07-31,626.7637,634.4683,625.4647,634.0816,103385200,-0.0038,623.1518,604.8437,4.0060,0.0043,0
2023-08-29,433.8349,434.1150,427.3635,427.5470,83081900,0.0145,428.6230,429.7790,6.0560,0.0083,1
2026-02-23,680.5315,688.1208,678.5170,685.9567,90558100,-0.0102,686.8996,685.2990,-8.2075,0.0078,1
2023-08-21,424.3500,425.0937,420.4671,422.6210,68719000,0.0065,432.7121,429.0366,-10.9820,0.0064,0
2026-02-09,692.0600,693.9748,686.4653,687.5423,73885200,0.0048,688.4872,684.3987,1.2167,0.0084,0
2024-04-03,507.0694,508.5728,505.3707,505.4195,59155800,0.0011,504.3089,492.5694,3.6120,0.0056,0
2023-02-13,395.7584,395.8926,391.3582,391.8184,64913500,0.0117,388.0614,379.1530,11.7339,0.0108,0
2025-03-31,553.0500,554.3551,540.6719,543.5984,95328200,0.0067,558.6513,579.5922,-5.9904,0.0129,1
2021-09-08,422.5201,423.2322,420.5991,422.5014,56181900,-0.0012,419.4700,412.9083,2.7550,0.0050,0
2025-08-14,639.5255,640.1898,636.9374,637.3836,59327500,0.0001,628.7270,614.4391,12.7618,0.0067,0
2026-02-17,680.9902,683.0745,673.9395,678.2876,81354700,0.0016,686.8298,685.0217,-12.5258,0.0090,1
2026-03-30,631.9700,640.3700,629.2800,640.1100,99275900,-0.0033,662.0813,676.7182,-35.2379,0.0093,1
2023-04-17,398.3369,398.3561,395.5943,396.8261,66436400,0.0036,388.9578,386.3608,4.3784,0.0078,1

#### **Prepare Dataset**

In [6]:
features = ['SMA20', 'SMA50', 'Momentum', 'Volatility']
X = data[features].dropna()
y = data['Target'].loc[X.index]
print(f"len(X) = {len(X)}")
print(f"len(y) = {len(y)}")

len(X) = 1207
len(y) = 1207

#### **Train Random Forest Model**

In [7]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100)
model.fit(X, y)

RandomForestClassifier()

#### ** Make Predictions**

In [8]:
predictions = model.predict(X)

#### **Evaluate Performance**

In [9]:
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y, predictions))

Accuracy: 1.0

#### **Feature Importance**

In [10]:
importance = pd.Series(model.feature_importances_, index=features)
display(importance.sort_values(ascending=False))

Momentum     0.2623
Volatility   0.2569
SMA50        0.2405
SMA20        0.2403
dtype: float64