In [1]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [2]:
# 1. Sales by Category (Bar Chart)
df_category = pd.DataFrame({
    "category": ["Jeans", "Shirts", "Jackets", "Dresses"],
    "sales": [1200, 950, 600, 800]
})
fig_bar = px.bar(df_category, x="category", y="sales")

display(df_category)

  category  sales
0    Jeans   1200
1   Shirts    950
2  Jackets    600
3  Dresses    800

In [3]:
# 2. Monthly Revenue Trend (Line Chart)
df_revenue = pd.DataFrame({
    "month": ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    "revenue": [50000, 42000, 60000, 55000, 70000, 68000]
})
fig_line = px.line(df_revenue, x="month", y="revenue", markers=True)

display(df_revenue)

  month  revenue
0   Jan    50000
1   Feb    42000
2   Mar    60000
3   Apr    55000
4   May    70000
5   Jun    68000

In [4]:
# 3. (Scatter Plot to show Inventory vs Sales)
df_inventory = pd.DataFrame({
    "product": ["Slim Jeans", "Linen Shirt", "Leather Jacket", "Summer Dress"],
    "inventory": [120, 150, 80, 200],
    "sales": [250, 180, 140, 300]
})
fig_scatter = px.scatter(df_inventory, x="inventory", y="sales", text="product", size="sales")

display(df_inventory)

          product  inventory  sales
0      Slim Jeans        120    250
1     Linen Shirt        150    180
2  Leather Jacket         80    140
3    Summer Dress        200    300

In [5]:
# 4. Pie Chart Regional Market Share
df_region = pd.DataFrame({
    "region": ["North", "South", "East", "West"],
    "sales": [30000, 25000, 15000, 20000]
})
fig_pie = px.pie(df_region, values="sales", names="region")

display(df_region)

  region  sales
0  North  30000
1  South  25000
2   East  15000
3   West  20000

In [6]:
# 2x2 grid one single dahsborad for all
fig = make_subplots(rows=2, cols=2,
                    subplot_titles=("Sales by Category", "Monthly Revenue Trend",
                                    "Inventory vs Sales", "Regional Market Share"),
                    specs=[[{"type": "bar"}, {"type": "xy"}],
                           [{"type": "xy"}, {"type": "domain"}]])

# Add traces from individual figures
for trace in fig_bar.data:
    fig.add_trace(trace, row=1, col=1)

for trace in fig_line.data:
    fig.add_trace(trace, row=1, col=2)

for trace in fig_scatter.data:
    fig.add_trace(trace, row=2, col=1)

for trace in fig_pie.data:
    fig.add_trace(trace, row=2, col=2)

# Layout
fig.update_layout(title_text="Syntra Clothing Brand Dashboard", height=800, showlegend=True)

fig.show()