### [ML in Finance: Time Series Momentum Analysis](https://medium.com/financial-engineering/ml-in-finance-series-time-series-momentum-analysis-in-python-bce455a03ccf)

In [1]:
!pip install -qq yfinance

In [2]:
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split, GridSearchCV, RepeatedKFold
from sklearn.preprocessing import MinMaxScaler

from IPython.display import display

import warnings
warnings.filterwarnings("ignore")

np.random.seed(42)
np.set_printoptions(precision=5, suppress=True)

pd.set_option("display.width", 200)
pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.6f}".format)

In [3]:
# Getting historical market data from SPY (ETF)
df = yf.download("SPY", start="2000-01-01", end="2025-01-01", progress=False, auto_adjust=True, threads=True)
display(df.sample(15))

Price           Close       High        Low       Open     Volume
Ticker            SPY        SPY        SPY        SPY        SPY
Date
2017-08-28 213.691879 214.242330 213.272472 214.216118   40565600
2014-07-21 162.213898 162.345421 161.465873 162.008397   67592000
2024-02-16 487.459503 490.738430 486.717828 489.596673   75532900
2020-01-21 303.591156 304.397560 303.151320 303.224616   77742400
2006-02-16  89.161453  89.195971  88.484934  88.595388   61017900
2013-04-10 127.240089 127.400470 126.005143 126.037215  135711100
2001-03-07  80.831161  80.869354  80.054550  80.780235    6371700
2016-10-06 185.714401 185.938170 184.819315 185.361525   62927400
2015-07-16 177.942795 177.942795 177.339314 177.582376  106683300
2024-01-10 465.063141 465.931684 462.438034 462.721046   67310600
2013-09-20 138.298508 139.602753 138.185096 139.602753  132867100
2002-06-27  64.511864  64.550791  62.656247  63.908464   31616400
2015-09-01 160.735229 163.249730 159.863529 161.866747  256000400
2016-04-22 178.023575 178.296179 177.120553 177.665774   99251700
2004-09-08  75.471283  75.793062  75.290278  75.498099   32963100

In [4]:
df["Ret"] = df["Close"].pct_change()

name = "Ret"

df["Ret10_i"] = (df[name].rolling(10).apply(lambda x: 100 * ((np.prod(1 + x)) ** (1 / 10) - 1)))
df["Ret25_i"] = (df[name].rolling(25).apply(lambda x: 100 * ((np.prod(1 + x)) ** (1 / 25) - 1)))
df["Ret60_i"] = (df[name].rolling(60).apply(lambda x: 100 * ((np.prod(1 + x)) ** (1 / 60) - 1)))
df["Ret120_i"] = (df[name].rolling(120).apply(lambda x: 100 * ((np.prod(1 + x)) ** (1 / 120) - 1)))
df["Ret240_i"] = (df[name].rolling(240).apply(lambda x: 100 * ((np.prod(1 + x)) ** (1 / 240) - 1)))
df = df.dropna()

df["Ret25"] = df["Ret25_i"].shift(-25)
df = df.dropna()

display(df.sample(15))

Price           Close       High        Low       Open     Volume       Ret   Ret10_i   Ret25_i   Ret60_i  Ret120_i  Ret240_i     Ret25
Ticker            SPY        SPY        SPY        SPY        SPY
Date
2018-07-16 248.635880 249.045310 248.190838 248.902921   48201000 -0.000894  0.293210  0.034427  0.071038 -0.004637  0.058464  0.089670
2004-10-27  75.987389  76.135487  74.802614  74.977634   73896000  0.012013  0.119489  0.047420  0.046830  0.014436  0.031584  0.234379
2020-07-02 289.065094 292.277649 288.398511 290.925949   69344200  0.005507  0.058348  0.138085  0.280243 -0.026674  0.027816  0.276805
2024-09-20 559.770386 560.814566 556.736330 559.366530   77503100 -0.001729  0.535311  0.120631  0.073198  0.075754  0.122274  0.075269
2012-01-31 102.567055 103.238743 102.067173 103.113785  157212000 -0.000380  0.152043  0.188842  0.106321  0.102429  0.000700  0.131028
2012-09-20 115.685806 115.748878 114.834188 115.149597  154009800  0.000068  0.202634  0.160339  0.176501  0.038519  0.105570 -0.125237
2022-11-11 381.322906 382.126675 376.634212 378.528829   93839900  0.009679  0.241312  0.376341 -0.111661  0.010340 -0.049478 -0.171563
2008-11-11  65.297653  67.021566  64.482982  66.017772  418498200 -0.030876 -0.433932 -0.431943 -0.585032 -0.357796 -0.197061  0.054007
2003-12-10  70.706192  70.871811  70.196082  70.732687   36915400 -0.000094  0.069596  0.036527  0.056331  0.062169  0.088163  0.290926
2008-01-23  95.851509  96.087810  90.824780  91.003794  511913000  0.024021 -0.369632 -0.357362 -0.201030 -0.066417 -0.025744  0.088988
2015-07-13 175.822205 175.931158 175.126525 175.168436  106069400  0.011037 -0.002385  0.019411  0.003327  0.038968  0.034396  0.015606
2020-02-26 285.447266 291.504416 284.714186 287.903113  194773800 -0.003678 -0.732375 -0.246195 -0.012985  0.056012  0.050527 -0.914177
2021-01-21 358.678925 359.341713 357.754792 358.912294   47840100  0.000912  0.282554  0.226478  0.183031  0.149191  0.068370 -0.040588
2012-03-29 110.006157 110.210127 109.111862 109.543323  164963700 -0.001709  0.008848  0.121595  0.166039  0.163612  0.033747 -0.093169
2018-10-11 243.350571 249.367929 241.732202 247.740638  274840500 -0.022027 -0.656146 -0.210068 -0.046031  0.024825  0.030290  0.012473

In [5]:
X, y = df.iloc[:, 0:-1], df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=int(len(y) * 0.5), shuffle=False
)

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

# Make predictions
y_pred = lin_reg.predict(X_train)
y_pred_test = lin_reg.predict(X_test)

score = lin_reg.score(X_train, y_train)
print(f"Score: {score:.6f}")

Score: 0.047768

In [6]:
print("In-Sample Performance:")
train_mse = mean_squared_error(y_train, y_pred)
train_r2 = r2_score(y_train, y_pred)
print(f"Mean squared error: {train_mse:.5f}")
print(f"Coefficient of determination (R2): {train_r2:.5f}")

print("\nOut-of-Sample Performance:")
test_mse = mean_squared_error(y_test, y_pred_test)
test_r2 = r2_score(y_test, y_pred_test)
print(f"Mean squared error: {test_mse:.5f}")
print(f"Coefficient of determination (R2): {test_r2:.5f}")

In-Sample Performance:
Mean squared error: 0.05033
Coefficient of determination (R2): 0.04777

Out-of-Sample Performance:
Mean squared error: 0.76791
Coefficient of determination (R2): -21.03935

In [7]:
# Train the model
e_net = ElasticNet(alpha=0.0001, l1_ratio=0.1)
e_net.fit(X_train, y_train)

# Make predictions
y_pred_elastic = e_net.predict(X_test)
elastic_mse = np.mean((y_pred_elastic - y_test) ** 2)
print(f"Mean Squared Error on test set (Elastic Net): {elastic_mse:.5f}")

Mean Squared Error on test set (Elastic Net): 0.60827

In [8]:
model = ElasticNet()
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
grid = dict()
grid["alpha"] = [1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 0.0, 1.0, 10.0, 100.0]
grid["l1_ratio"] = [0, 0.01, 0.1, 0.2, 0.5, 0.7, 1]
search = GridSearchCV(model, grid, scoring="neg_mean_squared_error", cv=cv, n_jobs=-1)
results = search.fit(X_train, y_train)

print(f"Best MSE: {results.best_score_:.3f}")
print(f"Best Config: {results.best_params_}")

Best MSE: -0.051
Best Config: {'alpha': 0.001, 'l1_ratio': 0.2}